### ISSUE TITLE
Kindle cloud reader translate does not work

### ISSUE THREAD

**Issue by alibatur** [motiko/kcr-translate-ext#2] opened 2019-11-25 20:50 UTC
I use chrome version 78.0.3904.108 (Official Build) (64-bit). It used to work before but suddenly stopped working. When a text is highlighted, I see only the note and highlight choices of the cloud reader, as if the extension is not existing, even though it is there and active.

**Comment by motiko** [comment] 2019-12-27 04:16
@alibatur can you please paste console logs output? 
Press Command+Option+J (Mac) or Control+Shift+J (Windows, Linux, Chrome OS)

**Comment by atrom** [comment] 2020-01-27 00:36
I sadly am also having trouble with chrome v.79.0.3945.117   I had been using it for a while, though it seemed to sometimes work and sometimes not.   But now nothing.   I'd be happy to help debug, what can I do to help ?

**Comment by motiko** [comment] 2020-01-27 11:05
Pasting the console log output would be a good start to see where the issue is

**Comment by motiko** [comment] 2020-01-27 11:20
Try this steps.
1. Press Control+Shift+J (Windows, Linux, Chrome OS) or Press Command+Option+J (Mac) 
to open developer console.
2. Refresh the page.
3. See if text "Kindle Translator Extension is now active."
Thank you.

**Comment by alibatur** [comment] 2020-01-27 12:27
now it is working, thanks a lot!

Moti Ko <notifications@github.com>, 27 Oca 2020 Pzt, 12:20 tarihinde şunu
yazdı:

**Comment by motiko** [comment] 2020-01-27 14:43
From what i can see refreshing the page while the book is opened solves it.
Will try to find why the refresh is required.
I will close the issue for now if there us still a problem feel free to reopen.
Don't forget to star this extension if you find it helpful 👍

**Closed by motiko** 2020-01-27 14:43 UTC

**Comment by alibatur** [comment] 2020-01-27 14:44
Thank you

27 Oca 2020 Pzt 15:43 tarihinde Moti Ko <notifications@github.com> şunu
yazdı:
